# Generated by Django 5.0.6 on 2024-07-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_payment_remove_order_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'credit')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
