# Generated by Django 5.0.6 on 2024-07-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_delete_payment_shippingaddress_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'credit')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
