# Generated by Django 5.0.6 on 2024-07-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'credit')], default='cash', max_length=20),
        ),
    ]
